### ISSUE TITLE
Fastify and binding to IPs doesn't work nicely

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1368]
Introduction of #1342 causes the following issue (which were no problem with express) see https://github.com/krausest/js-framework-benchmark/blob/master/server/index.js#L8:
If I don't bind fastify to 0.0.0.0 I can't access it on a VPS via a ssh tunnel.
If I bind fastify to 0.0.0.0 and run the server locally then 'npm run bench' can't access localhost:8080, though the URL works in the browser.

**Comment by nakrovati** [comment]
Damn, the simplest solution would be to replace localhost with 0.0.0.0 in benchmarkRunner.  By the way, this was fixed in nodejs 20, and using fetch you can access server 0.0.0.0 using the URL "localhost", in version 18 an error is thrown.

**Comment by krausest** [comment]
I decided to no longer access my VPS. I only did that for single framework updates, I couldn't get a stable ssh tunnel such that I could run all frameworks from the VPS. 
Now I'll use startLocalServerAndUpdateBuild.sh to create the build.zip on the VPS, transfer it to the local machine and start the server locally. This opens the chance that webdriver-ts-results/table.html can also be delivered by the server (and needs not to be opened from a file:// URL)

**Comment by krausest** [comment]
Holy shit. I had already something built in such that the HOST env variable can be used. Set to 0.0.0.0 I can't run the test driver due to the following error:
```
Executing frameworks/keyed/vanillajs and benchmark 21_ready-memory failed: Evaluation failed: TypeError: performance.measureUserAgentSpecificMemory is not a function
    at pptr://__puppeteer_evaluation_script__:1:13
Executing frameworks/keyed/vanillajs and benchmark 22_run-memory failed: Evaluation failed: TypeError: performance.measureUserAgentSpecificMemory is not a function
    at pptr://__puppeteer_evaluation_script__:1:13
Executing frameworks/keyed/vanillajs and benchmark 23_update5-memory failed: Evaluation failed: TypeError: performance.measureUserAgentSpecificMemory is not a function
    at pptr://__puppeteer_evaluation_script__:1:13
Executing frameworks/keyed/vanillajs and benchmark 25_run-clear-memory failed: Evaluation failed: TypeError: performance.measureUserAgentSpecificMemory is not a function
    at pptr://__puppeteer_evaluation_script__:1:13
Executing frameworks/keyed/vanillajs and benchmark 26_run-10k-memory failed: Evaluation failed: TypeError: performance.measureUserAgentSpecificMemory is not a function
    at pptr://__puppeteer_evaluation_script__:1:13
run was not completely sucessful Benchmarking failed with errors
```
Seems like chrome supports it only for localhost URLs.
I must be able to connect to the VPS if an implementations runs into an error.
I think I'll revert fastify until it works for a node LTS version.

**Comment by nakrovati** [comment]
Try running it again with Node 20.8.  There fetch resolves normally for localhost and 0.0.0.0.  It might work

**Comment by krausest** [comment]
Might work for the test driver. But do you think building all frameworks with node 20.8 will work? I think I can't ask contributors to use two node versions.

**Comment by nakrovati** [comment]
Maybe only frameworks with self-written bundlers break, while the rest use rollup, esbuild and webpack, which work with Node 20.

**Comment by krausest** [comment]
This is the first time ever that a node verions bump caused no new broken implemenntations. So we can require node 20.8.
